### ISSUE TITLE
Ui hung on detailed run and pathPrefix issue

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2968] opened 2023-07-19 16:43 UTC
I've updated to the latest version V0.13.0
When I click on a detailed run, the page is not responsive anymore.
I got
![image](https://github.com/kubeshop/tracetest/assets/4865355/5e3def65-8796-465d-9a44-b610d7d1a6ea)
If I wait long enough I got a response back

Also pathPrefix is not working for the liveness route, it return 404. I see in the yaml that liveness is on the prefix, but got 404 in the kubenretes events.
See also an old issue here https://github.com/kubeshop/tracetest/issues/2907

**Comment by jorgeepc** [comment] 2023-07-19 16:51
Hey @BartNetJS thank you for opening this issue. I am not able to reproduce the problem. Could you share more details about your `test`? The test definition file could help. Also, I am curious about the size of the response body of your trigger and the number of spans.

**Comment by BartNetJS** [comment] 2023-07-19 17:06
It's a very simple test:

```
type: Test
spec:
  id: integration-das-liveness
  name: DAS
  trigger:
    type: http
    httpRequest:
      url: http://someapiroute....
      method: GET
      headers:
      - key: Content-Type
        value: application/json
  specs:
  - selector: span[tracetest.span.type="general" name="Tracetest trigger"]
    assertions:
    - attr:tracetest.response.status = 200
```

First try:

![image](https://github.com/kubeshop/tracetest/assets/4865355/7b8c05d7-850a-4645-9dbd-192a77453258)

Past the url direct in another browser (chrome):

![image](https://github.com/kubeshop/tracetest/assets/4865355/5ec5e9b9-37b7-4077-ba7b-a7ae1d77fc0a)

Also tested in incognito: same result

Here i got a response after a long time:
![image](https://github.com/kubeshop/tracetest/assets/4865355/17e39c77-7672-4780-823e-095cd1d91b62)

Somethimes i got this:

![image](https://github.com/kubeshop/tracetest/assets/4865355/2bbaab00-e6c6-44f6-b1ac-42f51af4d6a7)

Logs from server seams ok

![image](https://github.com/kubeshop/tracetest/assets/4865355/df978873-1bc3-431a-bc16-0cc44c21fcea)

**Comment by BartNetJS** [comment] 2023-07-19 17:23
Maybe this one is also interesting:
![image](https://github.com/kubeshop/tracetest/assets/4865355/f9bfc58d-37bd-45f1-a202-2fe7f2c19f96)

**Comment by jorgeepc** [comment] 2023-07-19 17:56
@BartNetJS could you try using a clean install of tracetest `v0.13.0` and see if the bug is reproducible there?

A couple of questions:
- are you using docker or kubernetes?
- could you share the response from the GET `/api/tests/{TESTID}/run/{RUNID}` endpoint

**Comment by BartNetJS** [comment] 2023-07-19 18:18
@jorgeepc

I tried a clean install. Same issue.
Running on kubernetes in docker windows, but also updated the version on azure AKS with the same results

The http call gives an immediate response:

`
GET http://localhost:11633/test/casechanged-test-1/run/2 HTTP/1.1
User-Agent: vscode-restclient
accept-encoding: gzip, deflate



HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Date: Wed, 19 Jul 2023 18:11:51 GMT
Content-Length: 851
Connection: close

<!doctype html><html lang="en"><head><meta charset="utf-8"/><link href="./favicon.ico" rel="icon"/><meta content="width=device-width,initial-scale=1" name="viewport"/><meta content="#000000" name="theme-color"/><meta content="Integration test tool based on  opentelemetry traces" name="description"/><link href="./logo192.png" rel="apple-touch-icon"/><link href="./manifest.json" rel="manifest"/><title>Tracetest</title><script>const parser={toArray(e){try{return JSON.parse(e)||[]}catch(e){return[]}},toBoolean:e=>"true"===e,toObject(e){try{return JSON.parse(e)||{}}catch(e){return{}}},toString:e=>e};function getTemplateValue(e,t,r){var a=String.fromCharCode(123),n=`${a}${a}`;return!e||e.startsWith(n)?r(t):r(e)}function injectVariables(){window.ENV={measurementId:getTemplateValue("X2vwYODI1vb8g6QpzL9OBxuv5vK7dGan","",parser.toString),analyticsEnabled:getTemplateValue("true","false",parser.toBoolean),serverPathPrefix:getTemplateValue("/","/",parser.toString),serverID:getTemplateValue("dc2da8af7a","",parser.toString),appVersion:getTemplateValue("v0.13.0","",parser.toString),env:getTemplateValue("main","",parser.toString),experimentalFeatures:getTemplateValue("[]","[]",parser.toArray),isTracetestDev:getTemplateValue("false","false",parser.toBoolean)};var e=document.createElement("base");e.href=window.ENV.serverPathPrefix,document.getElementsByTagName("head")[0].appendChild(e)}injectVariables()</script><script defer="defer" src="./static/js/main.98b94208.js"></script><link href="./static/css/main.9b380086.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>
`

**Comment by BartNetJS** [comment] 2023-07-20 11:29
@jorgeepc I've downgraded to v0.12.2 and it runs smoothly again

**Comment by jorgeepc** [comment] 2023-07-21 13:34
Thank you @BartNetJS for the details. We are reviewing the problem and trying to duplicate it in our environments. We will let you know once we have more information.

**Comment by BartNetJS** [comment] 2023-08-01 08:36
@jorgeepc any update on this issue?
I've tested it also via a colleague, and hi has the same issue
If it could be a help, we can setup a meeting

**Comment by BartNetJS** [comment] 2023-08-02 06:51
Hi @jorgeepc 

Can i send you a mp4 file directly by mail or link?

**Comment by BartNetJS** [comment] 2023-08-03 05:40
@jorgeepc today is my last working day before holiday. If you send me a meeting request today (09:00-17:00 CET) I can show you the issue.

**Comment by jorgeepc** [comment] 2023-08-03 14:04
@BartNetJS I sent you an invite

**Comment by BartNetJS** [comment] 2023-08-23 13:33
HI @jorgeepc I'm back, but didn't got an invite. Can you try to send a new one?
I've also treid the latest version, still the same issue

**Comment by jorgeepc** [comment] 2023-08-23 23:12
Hey @BartNetJS please send me your contact details to jorge@kubeshop.io I'll schedule something for this week. Thank you!

**Comment by jorgeepc** [comment] 2023-09-06 18:15
Hey @BartNetJS I found the issue. I opened a PR #3127 with the fix. I'll notify you when we have it in a new release.

**Comment by jorgeepc** [comment] 2023-09-06 18:33
Reopening until we can validate it in the release

**Comment by jorgeepc** [comment] 2023-09-07 22:40
Hey @BartNetJS we release our `v0.13.7` version. Could you please double check if the issue is fixed? Thank you.

**Comment by jorgeepc** [comment] 2023-09-12 03:24
The problem was fixed in `v.0.13.7`. Closing this issue.

**Closed by jorgeepc** 2023-09-12 03:24 UTC
Labels: bug, triage, user-request
