### ISSUE TITLE
ElasticAPM examples are not working.

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2591] opened 2023-05-25 17:43 UTC
**Describe the bug**

When we are running the ElasticAPM example on `./examples/tracetest-elasticapm-with-elastic-agent` using `docker compose -f docker-compose.yaml up` all the containers runs after 5 mins. However, when running a test, out poller had a timeout when fetching traces.

Looking to the logs we have this:

```
tracetest-elasticapm-with-elastic-agent-apm-server-1      | {"log.level":"error","@timestamp":"2023-05-25T17:33:10.462Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":58},"message":"forbidden request","service.name":"apm-server","url.original":"/config/v1/agents?service.name=sample-app&service.environment=development","http.request.method":"GET","user_agent.original":"apm-agent-nodejs/3.46.0 (sample-app 1.0.0)","source.address":"172.19.0.6","http.request.body.bytes":0,"http.request.id":"28752a4a-1478-440f-bf52-fb7a2bb1fd98","event.duration":341566,"http.response.status_code":403,"error.message":"forbidden request: Agent remote configuration is disabled. Configure the `apm-server.kibana` section in apm-server.yml to enable it. If you are using a RUM agent, you also need to configure the `apm-server.rum` section. If you are not using remote configuration, you can safely ignore this error.","ecs.version":"1.6.0"}
tracetest-elasticapm-with-elastic-agent-apm-server-1      | {"log.level":"error","@timestamp":"2023-05-25T17:33:11.075Z","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":62},"message":"precondition 'apm integration installed' failed: error querying Elasticsearch for integration index templates: unexpected HTTP status: 404 Not Found ({\"error\":{\"root_cause\":[{\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"}],\"type\":\"resource_not_found_exception\",\"reason\":\"index template matching [logs-apm.error] not found\"},\"status\":404}): to remediate, please install the apm integration: https://ela.st/apm-integration-quickstart","service.name":"apm-server","ecs.version":"1.6.0"}

```

**Comment by jorgeepc** [comment] 2023-05-29 15:17
Hey @danielbdias I am not able to reproduce the issue. I tried running a test and it is working. I have a video with the demo here: https://www.loom.com/share/d092b260c58e41f9866b696bddc89c51

Please let me know if you have any other detail on how to reproduce the issue.

**Comment by jorgeepc** [comment] 2023-05-29 17:02
Confirmed with @danielbdias that the ElasticAPM example is working. Closing the ticket.

**Closed by jorgeepc** 2023-05-29 17:02 UTC
Labels: bug
