### ISSUE TITLE
[Error Handling] - Test runs take too long to time out when direct trace data store is misconfigured

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2327] opened 2023-04-07 16:06 UTC
When a trace data store such as Jaeger is setup wrong, tests still take 25 seconds to time out when max wait is set to 50s & retry delay is 500ms.

To reproduce, change the jaeger endpoint to a wrong port, such as jaeger-query.tracetest:16682
Run a test. 
The system quickly tells you that connectivity to jaeger failed (at around 5 secs) (highlighted portion of screen below
The system continues polling, and at 25 seconds gives up

Desired behaviour:
The polling should fail as soon as it sees that it cannot connect to the trace data store.

![image](https://user-images.githubusercontent.com/1385894/230640478-bdcc1604-58d3-4d5c-976f-bbdae9f7dd15.png)

**Comment by xoscar** [comment] 2023-04-17 18:22
@kdhamric I think you might have tested this in a version that wasn't fully ready, I'm not able to reproduce the issue in either beta or locally, will close this out but if you find the issue again please let us know!

**Closed** 2023-04-17 18:22 UTC
Labels: enhancement, backend, triage
