### ISSUE TITLE
Installing Tracetest resulted in an error

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/tracetest#1819] opened 2023-01-12 08:51 UTC
Running the `tracetest server install` command resulted in the following error: 

```sh
-> Let's check if your system has everything we need

✔ kubectl already installed
✔ helm already installed

-> Your system is ready! Now, let's configure TraceTest

Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?:
  > I have a tracing environment already. Just install Tracetest

panic: runtime error: slice bounds out of range [:10] with capacity 8

goroutine 1 [running]:
github.com/pterm/pterm.(*InteractiveSelectPrinter).Show(0x140000d4000, {0x0, 0x0, 0x8?})
	/home/runner/go/pkg/mod/github.com/pterm/pterm@v0.12.46/interactive_select_printer.go:116 +0x820
github.com/kubeshop/tracetest/cli/ui.ptermUI.Select({}, {0x100bdcff0, 0xf}, {0x140000d2180, 0x8, 0x140000d2180?}, 0x6)
	/home/runner/work/tracetest/tracetest/cli/ui/ui.go:154 +0x198
github.com/kubeshop/tracetest/cli/installer.configureKubernetes({0x140004bc390?, {0x100f1a500?, 0x10155b6c0?}}, {0x100f1a500, 0x10155b6c0})
	/home/runner/work/tracetest/tracetest/cli/installer/kubernetes.go:310 +0x270
github.com/kubeshop/tracetest/cli/installer.installer.Configure({{0x100bd9163, 0xa}, {0x101509990, 0x3, 0x3}, {0x10150b3e0, 0x4, 0x4}, 0x100f098e8}, {0x100f1a500, ...})
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:64 +0xf0
github.com/kubeshop/tracetest/cli/installer.installer.Install({{0x100bd9163, 0xa}, {0x101509990, 0x3, 0x3}, {0x10150b3e0, 0x4, 0x4}, 0x100f098e8}, {0x100f1a500, ...})
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:75 +0x150
github.com/kubeshop/tracetest/cli/installer.Start()
	/home/runner/work/tracetest/tracetest/cli/installer/installer.go:38 +0x27c
github.com/kubeshop/tracetest/cli/cmd.glob..func6(0x101518d20?, {0x10155ba78?, 0x0?, 0x0?})
	/home/runner/work/tracetest/tracetest/cli/cmd/server_install_cmd.go:21 +0x90
github.com/spf13/cobra.(*Command).execute(0x101518d20, {0x10155ba78, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x101518820)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/kubeshop/tracetest/cli/cmd.Execute()
	/home/runner/work/tracetest/tracetest/cli/cmd/root.go:30 +0x2c
main.main()
	/home/runner/work/tracetest/tracetest/cli/main.go:8 +0x20
```

**Comment by mathnogueira** [comment] 2023-01-12 17:07
Hey @aabedraba, I tried installing on minikube and I couldn't reproduce this issue. What are you using to run k8s?

**Comment by mathnogueira** [comment] 2023-01-13 15:25
We talked in a call and the problem is not happening anymore on his machine. I tried simulating the issue, but with no luck. I'll close it for now. @aabedraba if you have any trouble with the installer again, feel free to reopen this issue or open a new one.

**Closed by mathnogueira** 2023-01-13 15:25 UTC
Labels: bug, triage

**Comment by aabedraba** [comment] 2023-01-13 15:27
I should that the behavior changed when I removed a bunch of Kubernetes Contexts (from 8 to 3).

Thanks @mathnogueira
